name: lumberdash
description: >-
  Do you need logs? Lumberdash is the answer! With a simple but 
  powerful API, Lumberdash is the easiest way to record logs. And if 
  that is not enough, you can extend its API and create your own
  custom plugins for your own logging needs.
version: 1.0.0
author: Jorge Coca <jcocaramos@gmail.com>
homepage: https://github.com/jorgecoca/lumberdash

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  meta: ^1.0.0

dev_dependencies:
  test: ^1.4.0
  test_coverage: ^0.2.0
  mockito: ^4.0.0